version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gym_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=clave_secreta_para_docker

  frontend:
    build: ./frontend
    container_name: gym_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      # Aquí le decimos al frontend dónde está el backend dentro de la red de Docker
      - API_URL=http://backend:8000